name: elemental
main: net.rocketeer.elemental.ElementalPlugin
version: 0.0.1
depend: []
commands:
  heat:
    description: Heat release
    usage: /heat <temperature>
    permission: elemental.cmd
    permission-message: You don't have permission to do this!
  measure:
    description: Measure heat
    usage: /measure
    permission: elemental.cmd
    permission-message: You don't have permission to do this!